#!/bin/sh

CA_ARTIFACTORY_URL="https://bin.gov.pf/artifactory/ca"
CA_CERTINOMIS_URL="https://www.certinomis.fr/publi/cer"
CA_CERTIGNA_URL="http://autorite.certigna.fr"

CERT_URLS="$CA_ARTIFACTORY_URL/casit-prod2.crt \
    $CA_ARTIFACTORY_URL/casit.crt \
    $CA_CERTINOMIS_URL/AC_Racine_G3.cer \
    $CA_CERTINOMIS_URL/AC_2017_web.pem.cer \
    $CA_CERTINOMIS_URL/AC_CERTINOMIS_SSL.cer \
    $CA_CERTINOMIS_URL/AC_AGENTS.cer \
    $CA_CERTIGNA_URL/certignarootca.crt \
    $CA_CERTIGNA_URL/wildca.der \
    $CA_CERTIGNA_URL/certigna.der \
    $CA_CERTIGNA_URL/servicesca.crt"

for cert_url in $CERT_URLS
do
    cert_file="$(basename "$cert_url")"
    cert_path="/usr/local/share/ca-certificates/$cert_file"

    curl "$cert_url" -o "$cert_path"

    # Badly formatted certs break the entire file in alpine
    # Adds an eol char at the end of the file if not already present
    sed -i -e '$a\' "$cert_path"

    keytool -keystore cacerts -storetype jks -storepass changeit -noprompt -trustcacerts -importcert -alias "${cert_file%.*}" -file "$cert_path"
done

update-ca-certificates

keytool -importkeystore -srckeystore $JAVA_HOME/lib/security/cacerts -srcstorepass changeit -deststoretype jks -destkeystore /cacerts -deststoretype jks -deststorepass changeit -noprompt

BIN_JCE="https://bin.gov.pf/artifactory/public/jce"
for policy_jar in $(find / -name "local_policy.jar" -exec ls {} \;)
do
    curl "$BIN_JCE/local_policy.jar" > "$policy_jar"
done

for policy_jar in $(find / -name "US_export_policy.jar" -exec ls {} \;)
do
    curl "$BIN_JCE/US_export_policy.jar" > "$policy_jar"
done
