#!/bin/sh

CA_ARTIFACTORY_URL="https://bin.gov.pf/artifactory/ca"
CA_CERTINOMIS_URL="https://www.certinomis.fr/publi/cer"
CA_CERTIGNA_URL="http://autorite.certigna.fr"

CERT_URLS="$CA_ARTIFACTORY_URL/cadsi-prod.pem \
    $CA_CERTINOMIS_URL/AC_Racine_G3.cer \
    $CA_CERTINOMIS_URL/AC_2017_web.pem.cer \
    $CA_CERTINOMIS_URL/AC_CERTINOMIS_SSL.cer \
    $CA_CERTINOMIS_URL/AC_AGENTS.cer \
    $CA_CERTIGNA_URL/certignarootca.der \
    $CA_CERTIGNA_URL/wildca.der \
    $CA_CERTIGNA_URL/certigna.der \
    $CA_CERTIGNA_URL/servicesca.crt \
    $CA_CERTIGNA_URL/servicesca_rootca.crt \
    $CA_ARTIFACTORY_URL/Bundle_certificat_certigna.crt \
    $CA_ARTIFACTORY_URL/CertignaServerAuthenticationOVCPCAG1.crt"

mkdir -p /certificates

for cert_url in $CERT_URLS
do
    cert_file="$(basename "$cert_url")"
    cert_file="${cert_file%.pem}.crt"
    cert_path="/certificates/$cert_file"

    curl "$cert_url" -o "$cert_path"

    # Badly formatted certs break the entire file in alpine
    # Adds an eol char at the end of the file if not already present
    sed -i -e '$a\' "$cert_path"

    # 2nd part, install cert in ca-certificates
    cp /certificates/$cert_file /usr/local/share/ca-certificates/$cert_file
    keytool -keystore $JAVA_HOME/lib/security/cacerts -storepass changeit -noprompt -trustcacerts -importcert -alias "${cert_file%.*}" -file "/usr/local/share/ca-certificates/$cert_file"
    keytool -keystore cacerts -storepass changeit -noprompt -trustcacerts -importcert -alias "${cert_file%.*}" -file "/usr/local/share/ca-certificates/$cert_file"
done

update-ca-certificates

if test -f "$JAVA_HOME/lib/security/cacerts"; then
  keytool -importkeystore -srckeystore $JAVA_HOME/lib/security/cacerts -srcstorepass changeit -deststoretype jks -destkeystore /cacerts -deststoretype jks -deststorepass changeit -noprompt
else
  keytool -importkeystore -srckeystore $JAVA_HOME/jre/lib/security/cacerts -srcstorepass changeit -deststoretype jks -destkeystore /cacerts -deststoretype jks -deststorepass changeit -noprompt
fi
