name: Build Docker images

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions: [7, 8, 11]
        type: [jdk, jre]
        os: [alpine, debian]
    env:
      repo: "govpf/openjdk"
    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.5

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.6.0

    - name: Build and push debian
      uses: docker/build-push-action@v2.7.0
      if: matrix.os == 'debian'
      with:
        context: .
        file: ./${{ matrix.versions }}/${{ matrix.type }}/${{ matrix.os }}/Dockerfile
        platforms: linux/amd64
        pull: true
        push: false
        tags: |
          ${{ env.repo }}:${{ matrix.versions }}-${{ matrix.type }}-${{ matrix.os }}

    - name: Build and push version 8 (alpine only)
      uses: docker/build-push-action@v2.7.0
      if: matrix.os == 'alpine'
      with:
        context: .
        file: ./8/${{ matrix.type }}/${{ matrix.os }}/Dockerfile
        platforms: linux/amd64
        pull: true
        push: false
        tags: |
          ${{ env.repo }}:8-${{ matrix.type }}-${{ matrix.os }}
