name: Build Docker images

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions: [8, 11, 17, 21]
        type: [jdk, jre]
        os: [alpine, debian]
    env:
      repo: "govpf/openjdk"
    steps:

    - name: Checkout
      uses: actions/checkout@v3.4.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.6.1

    - name: Build and push debian
      uses: docker/build-push-action@v4.1.1
      with:
        context: .
        file: ./${{ matrix.versions }}/${{ matrix.type }}/${{ matrix.os }}/Dockerfile
        platforms: linux/amd64
        pull: true
        push: false
        tags: |
          ${{ env.repo }}:${{ matrix.versions }}-${{ matrix.type }}-${{ matrix.os }}
